# Generated by Django 4.1.6 on 2023-03-23 19:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(2022)])),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.alumno')),
                ('ciclo_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.ciclolectivo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
            options={
                'unique_together': {('ciclo_lectivo', 'alumno', 'curso')},
            },
        ),
    ]
